name: Docker Build on Tag Action
description: Build a docker image on a new repository ta

inputs:
  repository:
    description: name of the repository
    required: true
  ref:
    description: ref to checkout (default=main)
    default: main
    required: false
  tagfile:
    description: file to store the latest tag
    default: latest.txt
    required: false
  token:
    description: your github access token
    required: true
  docker_registry:
    description: the registry to push the image to
    default: hub.docker.com
    required: false
  docker_username:
    description: username to login
    required: true
  docker_password:
    description: password to login
    required: true
  docker_repository:
    description: repository to push the image to
    required: true
  dockerfile:
    description: the dockerfile
    default: Dockerfile
    required: false
  context:
    description: docker build context
    default: .
    required: false

branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - 
      name: Checkout Src
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        fetch-depth: 0
        path: ./src
    -
      name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ./repo
    -
      name: Switch WD
      shell: bash
      run: cd src
    -   
      name: Get Previous tag
      id: latesttag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0
    -
      name: Switch WD
      shell: bash
      run: cd ..
    - 
      name: Checkout Latest Tag
      shell: bash
      run: |
        TAGFILE=repo/${{ inputs.tagfile }}
        LATEST=${{ steps.latesttag.outputs.tag }}
        if [ -f "$TAGFILE" ]; then
          if [ "$LATEST" == $"$(cat $TAGFILE)" ]; then
            echo tag did not change, nothing to do.
            exit 0
          fi
        fi
        cd src
        git config --local advice.detachedHead false
        git checkout "$LATEST"
    -
      name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    -
      name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.docker_registry }}/${{ inputs.docker_repository }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    -
      name: Build and Push the Docker Image
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
    -
      name: Switch WD
      shell: bash
      run: cd ..
    -
      name: Set Latest Version to File
      shell: bash
      run: |
        TAGFILE=repo/${{ inputs.tagfile }}
        LATEST=${{ steps.latesttag.outputs.tag }}
        echo "$LATEST" > "$TAGFILE"
        cd repo
        git add .
        git commit -m "update to $LATEST"
        git push